spring.application.name=order-service
server.port=8082
server.shutdown=graceful
management.endpoints.web.exposure.include=*
management.info.git.mode=full
# Order Service Configs
order.catalog-service-url=http://localhost:8081
order.order-events-exchange=orders-exchange
order.new-orders-queue=new-orders
order.delivered-orders-queue=delivered-orders
order.cancelled-orders-queue=cancelled-orders
order.error-orders-queue=error-orders
# DB Configs
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:25432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.open-in-view=false
# RabbitMQ Configs
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}